package com.shoppilot.shoppilot.model;

public enum AuditEventType {
    INTENT_DETECTED,
    PRODUCT_RECOMMENDED,
    UPSELL_OFFERED,
    UPSELL_ACCEPTED,
    UPSELL_REJECTED,
    CUSTOMER_APPROVAL,
    RAZORPAY_ORDER_CREATED,
    PAYMENT_ATTEMPT,
    PAYMENT_SUCCESS,
    PAYMENT_FAILURE,
    ORDER_COMPLETED,
    AI_FALLBACK_TRIGGERED
}
